### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by davidebaldini** [nolanlawson/SimpleTalker#1]
I installed the precompiled APK you provided on an Android 4.1.2.
Running

```
adb shell am start -n com.nolanlawson.android.simpletalker/.MainActivity -e text "My text"
```

only results in a window appearing on the phone which shows the same text, with a button labelled "play it again, Sam". However, no sound is popped out.

**Comment by nolanlawson** [comment]
Have you installed the google TTS (text-to-speech) libraries from Google Play Services? In your settings, there should be something about TTS where you can test if it's possible to speak anything.

**Comment by davidebaldini** [comment]
Definitely, it works :)

Thanks for heading me to the point: one of my three or four volume control bars was leveled to zero, and not even the TTS example from the phone settings was working.
